### ISSUE TITLE
Broken message_d

### ISSUE THREAD

**Issue by johnjelliott** [kmlv/MoneyPolitics#50]
`message_d` is not considered a formfield despite being defined as one - See images below:
Also all old message_page_count and other archaic variables have been deleted from the HTML.

https://github.com/kmlv/MoneyPolitics/blob/daba9e3427bdb9c9d17d7f63949939fb61a8a7ce/pages.py#L60-L84

![SSS](https://user-images.githubusercontent.com/69054534/94223764-a0db3180-fea5-11ea-9ce2-7fe256e894f9.PNG)

https://github.com/kmlv/MoneyPolitics/blob/daba9e3427bdb9c9d17d7f63949939fb61a8a7ce/models.py#L297-L300

**Comment by mgutierrezc** [comment]
@johnjelliott , did that happen running the experiment under which `msg_type`? `single`, `double` or in both?

**Comment by mgutierrezc** [comment]
So this is causing the errors:

https://github.com/kmlv/MoneyPolitics/blob/daba9e3427bdb9c9d17d7f63949939fb61a8a7ce/templates/MoneyPolitics/PreparingMessage.html#L192-L206

You should only call `message_d` inside your template when you are on the `double` msg_type treatment and you are currently calling it always.

An if conditional inside the template like this inserted wherever you want to call `message_d` will help you solve it
```html
{% if msg_type == "double" %}

Code

{% endif %}
```

If you are wondering why you can call `msg_type` with that syntax, the answer is because it was defined on pages like this:

https://github.com/kmlv/MoneyPolitics/blob/daba9e3427bdb9c9d17d7f63949939fb61a8a7ce/pages.py#L140-L143

**Comment by johnjelliott** [comment]
I realized that issue this morning and corrected it but now I am running into the same problem with choices regardless of the session_config being in single or double. I will push my new code as well that has the message_d issue amended

**Comment by mgutierrezc** [comment]
Ok,  I dont think I receive notifications when doing commits in a branch diff than `master`. Please, notify me here with a comment when you do your push

**Comment by johnjelliott** [comment]
Both

**Comment by mgutierrezc** [comment]
I'll be looking at this now and tomorrow from 1:00 am GMT-5 to 3 am, and from 10 am to 3:30 pm GMT -5. Feel free to send me a message during those times

**Comment by johnjelliott** [comment]
Okay sounds good, Let me know if you find the error and I can take over
with finishing the updates. I think I am pretty close to done with the HTML
hookup with the exception of the form field issue

**Comment by mgutierrezc** [comment]
`elif` doesn't exist in this syntax. Try `elsif` instead

https://github.com/kmlv/MoneyPolitics/blob/f6ff0e38e85c2ae21261686d6a2a21377317dd34/templates/MoneyPolitics/PreparingMessage.html#L210

More details here:
https://metacpan.org/pod/Template::Liquid::Tag::If

**Comment by mgutierrezc** [comment]
Comment if there is any new error. Close and create a pull req with me as a reviewer to know if it's been solved 😃

**Comment by mgutierrezc** [comment]
Also, you cant call `choices` as a formfield from models, because it's a local variable created in`get_form_fields`  for storing all the receiver fields

https://github.com/kmlv/MoneyPolitics/blob/f6ff0e38e85c2ae21261686d6a2a21377317dd34/templates/MoneyPolitics/PreparingMessage.html#L216

When we are on the `single` message treatment, `choices` stores only the first message receiver fields: `income_9, income_15_1, income_15_2, ...` 

So, in your template, instead of calling `choices` call each of those fields manually

```
{% formfield player.income_9 %}

{% formfield player.income_15_1 %}

...
```

You'll have to also do that for the second message receiver fields (like `income_9_d`) in the `double` message treatment

**Comment by mgutierrezc** [comment]
> I'll be looking at this now and tomorrow from 1:00 am GMT-5 to 3 am, and from 10 am to 3:30 pm GMT -5. Feel free to send me a message during those times

I just remembered I had a medical appointment from 10 to 11:40 GMT -5

**Comment by johnjelliott** [comment]
No problem, I will fix this today and push the changes

**Comment by mgutierrezc** [comment]
This are my changes for the backend. Hope this helps!

https://github.com/kmlv/MoneyPolitics/blob/61d73d1bd5ebb8436918e7bc655954b743ef369d/pages.py#L85-L106

**Comment by mgutierrezc** [comment]
Try this instead 
https://github.com/kmlv/MoneyPolitics/blob/f6accf005e32112d4814da128e85e17706f7e61d/pages.py#L85-L115

**Comment by mgutierrezc** [comment]
Merge with my branch to get the fixed code:
https://github.com/kmlv/MoneyPolitics/blob/2c7190b6b6fe85e2bb75baf17b56affd8cd3b097/pages.py#L85-L120
